export { scrapeArwu } from "./arwu.ts";
export { scrapeCwur } from "./cwur.ts";
export { scrapeLeiden } from "./leiden.ts";
export { scrapeNature } from "./nature.ts";
export { scrapeNtu } from "./ntu.ts";
export { scrapeOpenalex } from "./openalex.ts";
export { scrapeQs } from "./qs.ts";
export { scrapeScimago } from "./scimago.ts";
export { scrapeTimes } from "./times.ts";
export { scrapeUsnews } from "./usnews.ts";
export { scrapeWebometrics } from "./webometrics.ts";
export type { ProviderOptions } from "./shared.ts";
